### PR TITLE
It's 2018, so you need a Dockerfile

### PR DESCRIPTION
**Pull request by beevee**
If you decide to accept this PR, I recommend you to configure autobuild on Docker Hub, so this container is available to everyone.

### CODE REVIEW

**Comment by parsifal-47** [comment]
@beevee do you create these animated gifs manually or there is a template and an engine for generation?

**Comment by beevee** [comment]
@parsifal-47 it’s a screencast recorded with http://recordit.co

**Comment by avasenin** [comment]
Thanks!

**Pull request merged**
